$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

if File.exist?(File.expand_path('../../../../lib/motion/project/cocoapods.rb', __FILE__))
  $:.unshift(File.expand_path('../../../../lib', __FILE__))
else
  require 'rubygems'
end
require 'motion-cocoapods'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RestKitTest'
  app.pods do
    pod 'RestKit'
  end
end
